### ISSUE TITLE
Mac OS X 10.6 compatibility

### ISSUE THREAD

**Issue by andreyz** [square/zapp#29]
Right now Zapp won't compile on Snow Leopard build server, due to the following use of OS X 10.7 APIs:

ZappAppDelegate.m:114:22: error: receiver type 'NSTableView' for instance message does not declare a method with selector 'rowForView:' [4]
     NSInteger row = [self.activityTableView rowForView:sender];
                      ^
ZappAppDelegate.m:150:98: error: use of undeclared identifier 'NSConfinementConcurrencyType' [3]
     NSManagedObjectContext *newContext = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSConfinementConcurrencyType];
                                                                                                  ^
ZappRepositoriesController.m:34:6: error: receiver type 'NSFileManager' for instance message does not declare a method with selector 'createDirectoryAtURL:withIntermediateDirectories:attributes:error:' [4]
     [fileManager createDirectoryAtURL:storageURL withIntermediateDirectories:YES attributes:nil error:NULL];
      ^

**Comment by ghost** [comment]
I was looking at this too, and I wasn't sure how much work would be required to get it running on 10.6. It also makes use of NSRegularExpression, which isn't in 10.6.

**Comment by andreyz** [comment]
You are right, I haven't noticed the use of NSRegularExpression. Will look more on what can be removed/replaced for 10.6 compatibility.

**Comment by puls** [comment]
The app is very highly dependent on a lot of 10.7 stuff. Making it work on 10.6 would be a colossal amount of work for marginal benefit.
